goog.provide( 'iAm.EnumPlatform' );

goog.require( 'iAm.DEFINE.MINIFY' );
goog.require( 'iAm.UNKNOWN_VALUE' );

/** @enum {string|number} */
iAm.EnumPlatform = {
    Unknown               : iAm.UNKNOWN_VALUE,
    NINTENDO_DS$TM        : iAm.DEFINE.MINIFY ?  1 : 'NintendoDS',
    NINTENDO_DSi$TM       : iAm.DEFINE.MINIFY ?  2 : 'NintendoDSi',
    NINTENDO_3DS$TM       : iAm.DEFINE.MINIFY ?  3 : 'Nintendo3DS',
    New_NINTENDO_3DS$TM   : iAm.DEFINE.MINIFY ?  4 : 'NewNintendo3DS',
    Wii$TM                : iAm.DEFINE.MINIFY ?  5 : 'Wii',
    WiiU$TM               : iAm.DEFINE.MINIFY ?  6 : 'WiiU',
    NINTENDO_SWITCH$TM    : iAm.DEFINE.MINIFY ?  7 : 'NintendoSwitch',
    PlayStation$RPortable : iAm.DEFINE.MINIFY ?  8 : 'PlayStationPortable',
    PlayStation$RVita     : iAm.DEFINE.MINIFY ?  9 : 'PlayStationVita',
    PlayStation$R3        : iAm.DEFINE.MINIFY ? 10 : 'PlayStation3', // PlayStation2 ?
    PlayStation$R4        : iAm.DEFINE.MINIFY ? 11 : 'PlayStation4',
    PlayStation$R5        : iAm.DEFINE.MINIFY ? 12 : 'PlayStation5',
    Xbox_360$TM           : iAm.DEFINE.MINIFY ? 13 : 'Xbox360',
    Xbox_One$TM           : iAm.DEFINE.MINIFY ? 14 : 'XboxOne',
    Xbox_SeriesX$VLS      : iAm.DEFINE.MINIFY ? 15 : 'XboxSeries',
    Feature_Phone         : iAm.DEFINE.MINIFY ? 16 : 'FeaturePhone',
    SONY_mylo             : iAm.DEFINE.MINIFY ? 17 : 'mylo',
    Rakuten_Kobo          : iAm.DEFINE.MINIFY ? 18 : 'Kobo',
    SONY_Reader$R         : iAm.DEFINE.MINIFY ? 19 : 'SonyReader',
    Kindle                : iAm.DEFINE.MINIFY ? 20 : 'Kindle',
    Windows_CE            : iAm.DEFINE.MINIFY ? 21 : 'WindowsCE',
    Windows_Mobile        : iAm.DEFINE.MINIFY ? 22 : 'WindowsMobile',
    Windows_Phone         : iAm.DEFINE.MINIFY ? 23 : 'WindowsPhone',
    iOS                   : iAm.DEFINE.MINIFY ? 24 : 'iOS',
    iPadOS                : iAm.DEFINE.MINIFY ? 25 : 'iPadOS',
    WatchOS               : iAm.DEFINE.MINIFY ? 26 : 'WatchOS', 
    Android               : iAm.DEFINE.MINIFY ? 27 : 'Android',
    Android_TV            : iAm.DEFINE.MINIFY ? 28 : 'AndroidTV',
    Google_TV             : iAm.DEFINE.MINIFY ? 29 : 'GoogleTV',
    FireOS                : iAm.DEFINE.MINIFY ? 30 : 'FireOS',
    ChromeOS              : iAm.DEFINE.MINIFY ? 31 : 'ChromeOS',
    FirefoxOS             : iAm.DEFINE.MINIFY ? 32 : 'FirefoxOS',
    KaiOS                 : iAm.DEFINE.MINIFY ? 33 : 'KaiOS',
    Symbian_OS_S60        : iAm.DEFINE.MINIFY ? 34 : 'SymbianS60',
    MeeGo                 : iAm.DEFINE.MINIFY ? 35 : 'MeeGo',
    Maemo                 : iAm.DEFINE.MINIFY ? 36 : 'Maemo',
    WebOS                 : iAm.DEFINE.MINIFY ? 37 : 'WebOS',
    Tizen                 : iAm.DEFINE.MINIFY ? 38 : 'Tizen',
    BlackBerry            : iAm.DEFINE.MINIFY ? 39 : 'BlackBerry',
    Windows16             : iAm.DEFINE.MINIFY ? 40 : 'Windows16',
    Windows               : iAm.DEFINE.MINIFY ? 41 : 'Windows',
    Mac                   : iAm.DEFINE.MINIFY ? 42 : 'Mac',
    SunOS                 : iAm.DEFINE.MINIFY ? 43 : 'SunOS',
    FreeBSD               : iAm.DEFINE.MINIFY ? 44 : 'FreeBSD',
    OpenBSD               : iAm.DEFINE.MINIFY ? 45 : 'OpenBSD',
    NetBSD                : iAm.DEFINE.MINIFY ? 46 : 'NetBSD',
    Ubuntu                : iAm.DEFINE.MINIFY ? 47 : 'Ubuntu',
    Mint                  : iAm.DEFINE.MINIFY ? 48 : 'Mint',
    Fedora                : iAm.DEFINE.MINIFY ? 49 : 'Fedora',
    Gentoo                : iAm.DEFINE.MINIFY ? 50 : 'Gentoo',
    Linux                 : iAm.DEFINE.MINIFY ? 51 : 'Linux'
};