/*
 Copyright 2020 itozyun, https://github.com/itozyun/what-browser-am-i, MIT License. */
var ua={conpare:function(q,l){var E=0,I;q=q.split(".");l=l.split(".");var Q=q.length,B=l.length;for(I=Q<B?Q:B;E<I;++E){var X=q[E]-0,R=l[E]-0;if(X!==R)return X>R?1:-1}return Q>B?1:Q===B?0:-1}};
(function(q,l,E,I,Q,B,X){function R(k,r,t){t=B(k.split(r)[1]);return 0<=t?t:0}function f(k,r){return 0<=k.indexOf(r)}function Fa(k){return f(k,"Linux armv")||f(k,"Linux aarch")||f(k,"Linux i686")||f(k,"Linux x86_64")}function ba(k,r){for(var t in r)if(t===k)return!0}function c(k,r){var t="",L=-1;if(k=k.split(r)[1]){for(;r=k.charCodeAt(++L);)if(48<=r&&57>=r||46===r)t+=k.charAt(L);else break;for(L=t.length;L;)if(46===t.charCodeAt(--L))t=t.substr(0,L);else break}return t}function Ga(){for(var k=arguments,
r=1,t=k[0],L;r<k.length;++r)0>Ha(t,L=k[r])&&(t=L);return t}function ca(k){return k===k+""?k:k===k-0?""+k:k.min&&k.max?k.min+"~"+k.max:k.min?k.min+"~":"~"+k.max}function da(k){return k===k+""?B(k):k}var Ha=q.conpare,a=I.userAgent,u=I.appVersion,oa=B(u)||0,p=I.platform,pa=E.documentElement,Ia=pa&&pa.style,qa=E.documentMode,ra=Q.width,sa=Q.height,Ja=l.HTMLAudioElement,Ka=l.performance,La=l.Int8Array,eb=void 0!==l.ontouchstart,M=c(u,"Version/")||c(a,"Version/"),Ma=l.operamini,S=!Ma&&l.opera,Na=S&&(S.version&&
"function"===typeof S.version?S.version():Ga(c(a,"Opera "),M,""+oa)),Oa=l.opr,W=!S&&(E.all||qa),F=W&&(qa?qa:l.XMLHttpRequest?E.getElementsByTagName?7:4:E.compatMode?6:(0).toFixed?5.5:l.attachEvent?5:4),ea=!W&&pa.msContentZoomFactor,T=!ea&&l.chrome,U=!W&&void 0!==Ia.MozAppearance,fa=f(a,"UCWEB"),fb=fa&&c(a," U2/"),gb=fa&&c(a,"; wds "),ta=c(a.split("_").join("."),"; iPh OS "),hb=c(a,"; Adr "),Pa=f(u,"YJApp-ANDROID"),G=f(p,"Android")||U&&f(u,"Android")||Pa,z=c(p,"Android ")||c(u,"Android ")||c(a,"Android ")||
hb,va=f(p,"Linux"),wa="MacIntel"===p&&void 0!==I.standalone,xa=U&&c(a,"Goanna/"),J=!xa&&U&&c(a,"rv:"),Qa=c(a,"Firefox/"),Ra=c(a,"Opera/"),Sa=l.FNRBrowser,v=R(a,"AppleWebKit/"),N=c(a,"Chrome/"),ha=c(a,"OPR/"),ib=c(u,"KHTML/"),Ta=c(a.toLowerCase(),"iris"),ya=c(a,"FxiOS/"),jb=c(a,"CriOS/"),kb=c(a,"EdgiOS/"),za=c(a,"Silk/"),V=R(a,"SamsungBrowser/"),Ua=!V&&function(){for(var k="GT-I9300 GT-I9305 SHV-E210 SGH-T999L SGH-I747 SGH-N064 SC-06D SGH-N035 SC-03E SCH-J021 SCL21 SCH-R530 SCH-I535 SCH-S960L SCH-S968C GT-I9308 SCH-I939 SHV-E210S GT-I8160 GT-I8260 GT-I8262 SM-G350 SM-G352 SM-G386F SM-G386T1GT-N7000 GT-N7005 SHV-E160 SC-05D SGH-N054 SGH-I717 SGH-T879 GT-I9220 GT-I9228 SCH-I889 GT-N7100 GT-N7105 SCH-I605 SCH-R950 SGH-I317 SGH-T889 SPH-L900 SCH-N719 GT-N7102 GT-N7108 SGH-N025 SC-02E SHV-E250 GT-N5100 GT-N5110 GT-N5120 GT-N8000 GT-N8005 GT-N8010 GT-N8013 GT-N8020 GT-I9100 GT-I9108 GT-I9210 SGH-I777 SGH-I757M SGH-I727 SGH-I927 SGH-T989 SHW-M250 SPH-D710 ISW11SC SC-02C SCH-R760 SCH-I929 GT-I9105 GT-I8190 GT-I8200 SM-G730A GT-P3100 GT-P3110 GT-P3113 SCH-I705 GT-P5100 GT-P5110 GT-P5113 SCH-I915 SM-G3508 SM-G3509 GT-S7580 GT-S7582 GT-S6310 GT-S6312 GT-S6313T".split(" "),
r,t=k.length;r=k[--t];)if(f(a,r))return 2>B(M)?M:.9;k="SC-02F SGH-N075 GT-S7270 GT-S7272 GT-S7275R GT-I9150 GT-I9152 GT-I9200 GT-I9205 GT-I9500 GT-I9506 SC-04E SGH-N045 GT-I9190 GT-I9192 GT-I9295 GT-I9197 GT-I9198 SGH-I257M SCH-I435 GT-I8666 GT-I8552 GT-I8558 SHV-E500S/L GT-18552B SM-N900 N9000 N9002 SC-01F SCL22 SM-G7100 SM-G7102 SM-G7105 SM-N750 SM-P600 SM-P601 SM-P605 GT-I9301I GT-I9300RWI SGH-T399 SM-P900 SM-P901 SM-P90 SM-P905 GT-I9295 SGH-I537 SHV-E330S GT-I9507V GT-I9505 GT-I9515 SGH-I337 SM-T230 SM-T231 SM-T235 SM-T237 403SC SM-T330NU SM-T331NU SM-T337V SM-T530 SM-T531 SM-T535 M-T320 SM-T321 SM-T325 SM-T520 SM-T525 SM-T900 SM-T905 SM-T700 SM-T705 SM-T707V SM-T800 SM-T805 SM-T807 SM-A300 SM-A5000 SM-A5009 SM-A500F SM-A500F1 SM-A500FQ SM-A500FU SM-A500G SM-A500H SM-A500HQ SM-A500K SM-G850 SM-C115 SM-C111 SM-G750F SM-G7508 SM-G7508Q SM-G750H GT-I9301I SM-900 SC-04F SCL23 SM-G906S SM-G906K SM-G906L SM-G870A SM-N915 SC-02G SM-800".split(" ");
for(t=k.length;r=k[--t];)if(f(a,r))return M}(),Va=T&&534.3>=v,Wa=Fa(p),lb=Wa&&!f(a,p)&&Fa(a),Xa=eb&&(v||U)&&lb||!z&&Pa,Ya=!!l.ReactNativeWebView,Za=Wa&&function(k){for(k in l)if(0===k.indexOf("SlexAPI_"))return!0}(),$a=l.puffinDevice,ia=$a&&$a.clientInfo,Y=ia&&"iOS"===ia.os&&ia.osVersion,ja=Y&&ia.model,Aa=!F&&E.registerElement,mb=!F&&E.execCommand,ab=va&&Aa&&"11.0.696.34"===N,nb=l._firefoxTV_playbackStateObserverJava,bb=R(a,"diordnA "),ob=null===l.onoperadetachedviewchange,C,b,Z,ka,Ba;if("Nitro"===
p)var h="NDS",H=!0;else if("Nintendo DSi"===p){h="NDSi";var g=Ra;H=!0}else if("New Nintendo 3DS"===p||f(a,"iPhone OS 6_0")&&320===ra&&240===sa)h="New3DS",g=c(a,"NintendoBrowser/"),H=!0;else if("Nintendo 3DS"===p){h="N3DS";g=c(a,"Version/");v=535;var pb=g;H=!0}else if("Nintendo Swicth"===p)h="Swicth",g=c(u,"NintendoBrowser/"),H=!0;else if("Nintendo WiiU"===p)h="WiiU",g=c(u,"NintendoBrowser/"),v=c(u,"AppleWebKit/"),H=!0;else if("Nintendo Wii"===p){h="Wii";g=c(a,"Wii; U; ; ");var d=h,e=g;H=!0}else if(b=
c(a,"PlayStation Vita "))h="PSVita",g=b,d=h,e=b,H=!0;else if(b=c(a,"(PlayStation Portable); ")){h="PSP";g=b;var cb=3.3;d=h;e=b;H=!0}else if(b=c(a,"PLAYSTATION 3; ")||c(a,"PLAYSTATION 3 ")){h="PS3";g=b;d=h;e=b;if(0>Ha("4.10",b))var m="Sony",n=b;H=!0}else if(f(a,"Xbox One"))h="XboxOne",g=1,H=!0;else if(f(a,"Xbox"))h="Xbox360",g=1,H=!0;else if(2===oa&&f(a,"Sony/COM2/")){h="Mylo";g=2;cb=3.4;d=h;e=2;var aa=!0}else if(0===p.indexOf("iP")||ta||Y||wa){if(Y)switch(g=Y,ja.substr(0,4)){case "iPho":var w="iPhone",
O=c(ja,w),D=!0;break;case "iPad":w="iPad";O=c(ja,w);var x=!0;break;case "iPod":w="iPod";O=c(ja,w);var Ca=!0}else{if(ta)g=ta;else{g=c(u.split("_").join("."),"OS ");var qb=!ba("isSecureContext",l),rb=ba("enableWebGL",l),sb=ba("sameOrigin",l)}g||(C=!0);if(!g||Sa)g=l.PointerEvent?13:l.HTMLDataListElement?12.2:Array.prototype.flat?12:I.sendBeacon?11.3:l.WebAssembly?11.2:l.HTMLMeterElement?10.3:l.Proxy?10.2:l.HTMLPictureElement?9.3:X.isNaN?9.2:l.SharedWorker?Ka&&Ka.now?8:8.4:mb?7.1:l.webkitURL?6.1:l.Worker?
5.1:La?4.3:Ja?4.1:3.2;var Da=1===l.devicePixelRatio,y=ra===1.5*sa||1.5*ra===sa;0===p.indexOf("iPhone")?(w="iPhone",O=y?Da?{max:3}:{min:4,max:5}:{max:6},D=!0):0===p.indexOf("iPad")||wa?(w="iPad",O=Da?{max:2}:{min:3},x=!0):0===p.indexOf("iPod")&&(w="iPod",O=y?Da?{max:3}:4:{min:5},Ca=!0)}if(!Y&&(I.standalone||(x||12>g)&&ba("webkitFullscreenEnabled",E)||11<=g&&13>g&&I.mediaDevices))m="SafariMobile",d="Safari",e=g;else{var Ea=!0;m="iOSWebView"}h="iOS";n=g}else if(f(a,"Kobo"))h="Kobo",m="AOSP",n=2.2,d=
m,e=n,G=ka=!0;else if(f(a,"EBRD"))h="SonyReader",m="AOSP",n=2.2,d=m,e=n,ka=!0;else if(b=c(a,"CrOS x86_64 ")||c(a,"CrOS aarch64 ")||c(a,"CrOS i686 ")||c(a,"CrOS armv7l ")){h="ChromeOS";g=b;var la=!0}else if(void 0!==l.onmoztimechange)h="FirefoxOS",g=18.1>J?"1.0.1":19>J?1.1:27>J?1.2:29>J?1.3:31>J?1.4:33>J?2:35>J?2.1:38>J?2.2:45>J?2.5:2.6,f(a,"Mobile")?D=!0:f(a,"Tablet")?x=!0:f(a,"TV")&&(Z=!0);else if(l.palmGetResource)h="webOS",g=c(a,"webOS/")||c(a,"WEBOS")||c(a,"hpwOS/"),d=h,e=g,f(a,"webOS.TV")||f(a,
"/SmartTV")?Z=!0:D=!0;else if(b=c(a,"Tizen "))h="Tizen",g=b,d="Samsung",e=V,m=d,n=e,D=!0;else if(b=c(a,"Windows Phone ")||c(u,"Windows Phone OS ")||gb){var ma=!0;g=b;D=!0}else if(ea&&"ARM"===p)ma=!0,g=10,C=D=!0;else if(W&&f(u,"ZuneWP"))ma=!0,g=11===F?8.1:10===F?8:9===F?7.5:7===F?7:"?",C=D=!0;else if(f(a,"FOMA;"))h="FeaturePhone",D=!0;else if(f(a,"SoftBank;"))h="FeaturePhone",D=!0;else if(f(a,"KFMUWI")){var K=!0;g=6.3;var A=x=!0}else if(f(a,"KFKAWI"))K=!0,g=6,A=x=!0;else if(f(a,"KFSUWI")||f(a,"KFAUWI")||
f(a,"KFDOWI"))K=!0,g=5,A=x=!0;else if(f(a,"KFGIWI"))K=!0,g=5,A=x=!0;else if(f(a,"KFARWI")||f(a,"KFSAWA")||f(a,"KFSAWI"))K=!0,g=5<=B(z)?5:4,A=x=!0;else if(f(a,"KFSOWI")||f(a,"KFTHWA")||f(a,"KFTHWI")||f(a,"KFAPWA")||f(a,"KFAPWI"))K=!0,g=3,A=x=!0;else if(f(a,"KFOT")||f(a,"KFTT")||f(a,"KFJWA")||f(a,"KFJWI"))K=!0,g=2,A=x=!0;else if(f(a,"Kindle Fire"))K=!0,g=1,A=x=!0;else if(b=c(a,"Kindle/"))h="Kindle",g=b,m="AOSP",n=2.2,d=m,e=n,ka=!0;else if(nb)K=!0,g=z||bb,A=Z=!0,C=bb;else if(f(a,"AmazonWebAppPlatform")||
f(a,"; AFT"))K=!0,g=z,A=Z=!0;else if(f(a,"MeeGo"))h="MeeGo";else if(f(a,"Maemo"))h="Maemo";else if(0===a.indexOf("Windows Mobile;")||Ta)h="WindowsMobile",aa=!0;else if("WinCE"===p)h=p,aa=!0;else if("Win16"===p||"Win32"===p||"Win64"===p)h=p,g=c(a,"Windows NT ")||c(a,"Windows "),la=!0;else if(0===p.indexOf("Mac")){h="MacPowerPC"===p?"MacPPC":p;if(b=c(a.split("_").join("."),"Mac OS X "))g=b;var db=la=!0}else if(f(a,"BlackBerry")||f(a,"BB10"))h="BlackBerry",g=M,D=!0;else if(f(a,"SunOS")||f(a,"Sun Solaris"))h=
"SunOS",la=!0;else if(f(a,"FreeBSD"))h="FreeBSD";else if(f(a,"OpenBSD"))h="OpenBSD";else if(f(a,"NetBSD"))h="NetBSD";else if(G&&U)f(a,"Android 4.4;")?y={min:2.3}:4<=B(z)?y=z:y={min:2.2},g=y,Xa&&(C=!0);else if(G&&S)z?y=z:(y={min:1.6},C=!0),g=y,f(a,"Tablet")?x=!0:D=!0;else if(z)g=z,G=!0;else if(va&&Xa||Ya||Za){var P=!0;V?y={min:4.4}:T&&!Va||Oa||ha?y={min:4}:(y=z=void 0!==Ia.touchAction?{min:5}:Aa?4.4:La?I.connection?l.searchBoxJavaBridge_||T?X.isNaN?4.1:4:4.2:4.4:534<=v?3:533<=v?Ja?2.3:2.2:530<=v?2:
1.5,Ua&&(m="Samsung",n=Ua));g=y;G=!0}else ab?(g={min:5},P=G=!0):va&&(f(a,"Ubuntu")?h="Ubuntu":(b=c(a,"Mint/"))?(h="Mint",g=b):(b=c(a,"Fedora/"))?(h="Fedora",g=b):h=f(a,"Gentoo")?"Gentoo":"Linux");K||G&&P&&za?h="FireOS":G&&(h=h||"Android");ma&&(h="WindowsPhone");if(!m)if(A=A||G,S)m=A||aa||D||x?"PrestoMobile":"Presto",n=Na;else if(W)(y=R(u,"Trident/")+4)&&y!==F&&(d="IEHost",e=y),10<=F&&6.2<=g&&7>g&&0===screenY&&innerHeight+1!==outerHeight&&(d="ModernIE",e=F),aa||D||x||Ca?m="TridentMobile":db&&5<=F?
(m="Tasman",d="MacIE",e=F):(m="Trident",db&&(d="MacIE",e=F)),n=F;else if(ea)m=ma?"EdgeMobile":"EdgeHTML",n=c(u,"Edge/");else if(xa)m="Goanna",n=xa;else if(U)m=A?"Fennec":"Gecko",n=J||Qa;else if(V)m="Samsung",n=V,P&&(C=!0);else if(b=cb||c(a,"NetFront/"))m="NetFront",n=b;else if(b=c(a,"iCab"))m="iCab",n=b;else if(b=Ga(c(a,"Opera Mini/"),c(a,"Opera Mobi/"))||Ma&&M)m="OperaMini",n=b,h||(f(a,"iPhone")?w="iPhone":f(a,"iPad")?w="iPad":f(a,"iPod")&&(w="iPod"),w&&(h="iOS"));else if(fa)m="UCWEB",n=fb;else if(ib)m=
"KHTML",n=oa;else if(G&&Va){m="AOSP";n=z;var na=!0;P&&(C=!0)}else T||Oa||ha?(m=A?"ChromiumMobile":"Chromium",n=N,P&&(C=!0)):G&&Aa?(m="ChromeWebView",n=5>B(z)?z:N,na=!0,l.requestFileSystem||l.webkitRequestFileSystem||(Ba=!0),P&&(C=!0)):G&&(M||P)?(m="AOSP",n=z,na=!0,P&&(C=!0)):N?(m=A?"ChromiumMobile":"Chromium",n=N):v&&(m="WebKit",n=v);d||((b=ea&&c(a,"Edge/")||c(a,"EdgA/")||kb||c(a,"Edg/"))?(d="Edge",e=b):(b=c(u,"Coast/"))?(d="Coast",e=b):qb?d="OperaTurbo":(b=c(u,"OPT/"))?(d="OperaTouch",e=b,C=C||!f(u,
"Mobile/")):(b=c(a.toLowerCase(),"ybrowser/"))?(d="Yahoo",e=b):!fa&&(b=c(a,"UCBrowser/"))?(d="UC",e=b):za?(d="Silk",e=za):(b=c(a,"Vivaldi/"))?(d="Vivaldi",e=b):(b=c(a,"QQBrowser/"))?(d="QQ",e=b):(b=c(a,"YaBrowser/"))?(d="Yandex",e=b):(b=c(a,"coc_coc_browser/"))?(d="coccoc",e=b):(b=c(a,"Camino/"))?(d="Camino",e=b):f(a,"SE 2.X MetaSr 1.0")?d="Sogou":(b=c(a,"Focus/")||c(a,"Klar/")||9>B(ya)&&Ea&&11<=B(g)&&ya)?(d="Focus",e=b):(b=c(a,"AOLBUILD/")||c(a,"AOL/")||c(a,"AOL "))?(d="AOL",e=b):(b=c(a,"IceDragon/"))?
(d="IceDragon",e=b):(b=c(a,"Iceweasel/"))?(d="Iceweasel",e=b):(b=c(a,"TenFourFox/"))?(d="ITenFourFox",e=b):(b=c(a,"Waterfox/"))?(d="Waterfox",e=b):(b=c(a,"GNUzilla/"))?(d="GNUzilla",e=b):(b=c(a,"SeaMonkey/"))?(d="SeaMonkey",e=b):(b=c(a,"PaleMoon/"))?(d="PaleMoon",e=b):(b=c(a,"Basilisk/"))?(d="Basilisk",e=b):(b=c(a,"Maxthon/")||c(a,"Maxthon ")||c(a,"MXiOS/"))||f(a,"Maxthon")?(d="Maxthon",e=b||1):f(a,"Avant Browser;")?d="Avant":(b=c(a,"Konqueror/"))?(d="Konqueror",e=b):(b=c(a,"Midori/"))?(d="Midori",
e=b):(b=c(a,"OmniWeb/"))?(d="OmniWeb",e=b):(b=c(a,"Roccat/"))?(d="Roccat",e=b):(b=c(a,"Epiphany/"))?(d="Epiphany",e=b):(b=c(a,"WebPositive/"))?(d="WebPositive",e=b):(b=c(a,"Iron/"))||f(a," Iron ")?(d="Iron",e=b||T&&N):(b=c(a,"Comodo Dragon/"))?(d="ComodoDragon",e=b):(b=c(a,"Brave/"))||f(a," Brave ")||sb?(d="Brave",e=b||T&&N):(b=c(a,"Rockmelt/"))?(d="Rockmelt",e=b):(b=c(a,"Sleipnir/"))||Sa||Za?(d="Sleipnir",b&&(e=b)):rb?d="Dolphin":(b=c(a,"Puffin/"))?(d="Puffin",e=b):(b=c(a,"Dooble/"))?(d="Dooble",
e=b):(b=c(a,"Flock/"))?(d="Flock",e=b):(b=c(a,"Galeon/"))?(d="Galeon",e=b):(b=c(a,"Falkon/"))?(d="Falkon",e=b):(b=c(a,"Iceape/"))?(d="Iceape",e=b):(b=c(a,"K-Meleon/"))?(d="KMeleon",e=b):(b=pb||c(u,"NX/"))?(d="NetFrontNX",e=b):(b=c(a,"Netscape6/")||c(a,"Netscape/")||c(a,"Navigator/"))?(d="NN",e=b):Ta?(d="Iris",e=b):(b=c(a,"FBAV/")||f(u,"FBAN/"))?(d="Facebook",e=b):(b=c(u,"Line/"))?(d="LINE",e=b):(b=c(a,"QtWebEngine/"))?(d="QtWebEngine",e=b):(b=c(a,"QtWebKit/"))?(d="QtWebKit",e=b):(b=c(a,"DuckDuckGo/"))?
(d="DuckDuckGo",e=b):(b=c(a,"Lunascape/")||Ya)?(d="Lunascape",e=b):(b=ya||U&&(Qa||n))?(d="Firefox",e=b):ob?(d="OperaGX",e=ha):(b=Na||ha||Ra)?(d="Opera",e=b):W?(d="IE",e=n):V?(d=m,e=V):(b=jb||(T||ab&&na)&&N)?(d="Chrome",e=b):na&&!Ba?(d=m,e=n):Ea&&!x?(m="SafariMobile",d="Safari",e=g):Ea||Ba||!f(a,"Safari")&&!M||(d="Safari",e=M||(73>v?.8:85>v?.9:100>v?1:125>v?1.1:312>v?1.2:412>v?1.3:419.3>=v?2:525.13>=v?3:525.25>=v?3.1:3.2)),d=d||"unknown");h&&(q.PLATFORM=h,g?(q.PLATFORM_VERSION=ca(g),q[h]=da(g)):q[h]=
!0);m&&(q.ENGINE=m,n?(q.ENGINE_VERSION=ca(n),q[m]=da(n)):q[m]=!0,d||(d=m,e=n));d&&(q.BRAND=d,e?(q.BRAND_VERSION=ca(e),q[d]=da(e)):q[d]=!0);w&&(q.DEVICE=w,O?(q.DEVICE_VERSION=ca(O),q[w]=da(O)):q[w]=!0);if(C||wa)q.PCSITE_REQUESTED=!0;q.DEVICE_TYPE=aa?8:H?7:Z?6:Ca?5:ka?4:D?2:x?3:la?1:0})(ua,window,document,navigator,screen,parseFloat,Number);module.export=ua;
