/*
 Copyright 2020 itozyun, https://github.com/itozyun/what-browser-am-i, MIT License. */
whatBrowserAmI={};
(function(Ga){Ga.conpare=function(q,l){var E=0,I;q=q.split(".");l=l.split(".");var Q=q.length,B=l.length;for(I=Q<B?Q:B;E<I;++E){var X=q[E]-0,R=l[E]-0;if(X!==R)return X>R?1:-1}return Q>B?1:Q===B?0:-1};(function(q,l,E,I,Q,B,X){function R(k,v,r){r=B(k.split(v)[1]);return 0<=r?r:0}function f(k,v){return 0<=k.indexOf(v)}function Ha(k){return f(k,"Linux armv")||f(k,"Linux aarch")||f(k,"Linux i686")||f(k,"Linux x86_64")}function ba(k,v){for(var r in v)if(r===k)return!0}function c(k,v){var r="",L=-1,ca;if(k=
k.split(v)[1]){for(;ca=k.charCodeAt(++L);)if(48<=ca&&57>=ca||46===ca)r+=k.charAt(L);else break;for(L=r.length;L;)if(46===r.charCodeAt(--L))r=r.substr(0,L);else break}return r}function Ia(){for(var k=arguments,v=1,r=k[0],L;v<k.length;++v)0>Ja(r,L=k[v])&&(r=L);return r}function da(k){return k===k+""?k:k===k-0?""+k:k.min&&k.max?k.min+"~"+k.max:k.min?k.min+"~":"~"+k.max}function ea(k){return k===k+""?B(k):k}var Ja=q.conpare,a=I.userAgent,t=I.appVersion,pa=B(t)||0,p=I.platform,qa=E.documentElement,Ka=
qa&&qa.style,ra=E.documentMode,sa=Q.width,ta=Q.height,La=l.HTMLAudioElement,Ma=l.performance,Na=l.Int8Array,gb=void 0!==l.ontouchstart,M=c(t,"Version/")||c(a,"Version/"),Oa=l.operamini,S=!Oa&&l.opera,Pa=S&&(S.version&&"function"===typeof S.version?S.version():Ia(c(a,"Opera "),M,""+pa)),Qa=l.opr,W=!S&&(E.all||ra),F=W&&(ra?ra:l.XMLHttpRequest?E.getElementsByTagName?7:4:E.compatMode?6:(0).toFixed?5.5:l.attachEvent?5:4),fa=!W&&qa.msContentZoomFactor,T=!fa&&l.chrome,U=!W&&function(k){for(k in Ka)if(0===
k.indexOf("Moz"))return!0}(),ha=f(a,"UCWEB"),hb=ha&&c(a," U2/"),ib=ha&&c(a,"; wds "),va=c(a.split("_").join("."),"; iPh OS "),jb=c(a,"; Adr "),Ra=f(t,"YJApp-ANDROID"),G=f(p,"Android")||U&&f(t,"Android")||Ra,z=c(p,"Android ")||c(t,"Android ")||c(a,"Android ")||jb,wa=f(p,"Linux"),xa="MacIntel"===p&&void 0!==I.standalone,ya=U&&c(a,"Goanna/"),J=!ya&&U&&(c(a,"rv:")||c(a.substr(a.indexOf(") Gecko/")-11),"; ")),Sa=c(a,"Firefox/"),Ta=c(a,"Opera/"),Ua=l.FNRBrowser,u=R(a,"AppleWebKit/"),N=c(a,"Chrome/"),ia=
c(a,"OPR/"),kb=c(t,"KHTML/"),Va=c(a.toLowerCase(),"iris"),za=c(a,"FxiOS/"),lb=c(a,"CriOS/"),mb=c(a,"EdgiOS/"),Aa=c(a,"Silk/"),V=R(a,"SamsungBrowser/"),Wa=!V&&function(){for(var k="GT-I9300 GT-I9305 SHV-E210 SGH-T999L SGH-I747 SGH-N064 SC-06D SGH-N035 SC-03E SCH-J021 SCL21 SCH-R530 SCH-I535 SCH-S960L SCH-S968C GT-I9308 SCH-I939 SHV-E210S GT-I8160 GT-I8260 GT-I8262 SM-G350 SM-G352 SM-G386F SM-G386T1GT-N7000 GT-N7005 SHV-E160 SC-05D SGH-N054 SGH-I717 SGH-T879 GT-I9220 GT-I9228 SCH-I889 GT-N7100 GT-N7105 SCH-I605 SCH-R950 SGH-I317 SGH-T889 SPH-L900 SCH-N719 GT-N7102 GT-N7108 SGH-N025 SC-02E SHV-E250 GT-N5100 GT-N5110 GT-N5120 GT-N8000 GT-N8005 GT-N8010 GT-N8013 GT-N8020 GT-I9100 GT-I9108 GT-I9210 SGH-I777 SGH-I757M SGH-I727 SGH-I927 SGH-T989 SHW-M250 SPH-D710 ISW11SC SC-02C SCH-R760 SCH-I929 GT-I9105 GT-I8190 GT-I8200 SM-G730A GT-P3100 GT-P3110 GT-P3113 SCH-I705 GT-P5100 GT-P5110 GT-P5113 SCH-I915 SM-G3508 SM-G3509 GT-S7580 GT-S7582 GT-S6310 GT-S6312 GT-S6313T".split(" "),
v,r=k.length;v=k[--r];)if(f(a,v))return 2>B(M)?M:.9;k="SC-02F SGH-N075 GT-S7270 GT-S7272 GT-S7275R GT-I9150 GT-I9152 GT-I9200 GT-I9205 GT-I9500 GT-I9506 SC-04E SGH-N045 GT-I9190 GT-I9192 GT-I9295 GT-I9197 GT-I9198 SGH-I257M SCH-I435 GT-I8666 GT-I8552 GT-I8558 SHV-E500S/L GT-18552B SM-N900 N9000 N9002 SC-01F SCL22 SM-G7100 SM-G7102 SM-G7105 SM-N750 SM-P600 SM-P601 SM-P605 GT-I9301I GT-I9300RWI SGH-T399 SM-P900 SM-P901 SM-P90 SM-P905 GT-I9295 SGH-I537 SHV-E330S GT-I9507V GT-I9505 GT-I9515 SGH-I337 SM-T230 SM-T231 SM-T235 SM-T237 403SC SM-T330NU SM-T331NU SM-T337V SM-T530 SM-T531 SM-T535 M-T320 SM-T321 SM-T325 SM-T520 SM-T525 SM-T900 SM-T905 SM-T700 SM-T705 SM-T707V SM-T800 SM-T805 SM-T807 SM-A300 SM-A5000 SM-A5009 SM-A500F SM-A500F1 SM-A500FQ SM-A500FU SM-A500G SM-A500H SM-A500HQ SM-A500K SM-G850 SM-C115 SM-C111 SM-G750F SM-G7508 SM-G7508Q SM-G750H GT-I9301I SM-900 SC-04F SCL23 SM-G906S SM-G906K SM-G906L SM-G870A SM-N915 SC-02G SM-800".split(" ");
for(r=k.length;v=k[--r];)if(f(a,v))return M}(),Xa=T&&534.3>=u,Ya=Ha(p),nb=Ya&&!f(a,p)&&Ha(a),Za=gb&&(u||U)&&nb||!z&&Ra,$a=!!l.ReactNativeWebView,ab=Ya&&function(k){for(k in l)if(0===k.indexOf("SlexAPI_"))return!0}(),bb=l.puffinDevice,ja=bb&&bb.clientInfo,Y=ja&&"iOS"===ja.os&&ja.osVersion,ka=Y&&ja.model,Ba=!F&&E.registerElement,ob=!F&&E.execCommand,cb=wa&&Ba&&"11.0.696.34"===N,pb=l._firefoxTV_playbackStateObserverJava,db=R(a,"diordnA "),qb=null===l.onoperadetachedviewchange,C,b,Z,la,Ca;if("Nitro"===
p)var h="NDS",H=!0;else if("Nintendo DSi"===p){h="NDSi";var g=Ta;H=!0}else if("New Nintendo 3DS"===p||f(a,"iPhone OS 6_0")&&320===sa&&240===ta)h="New3DS",g=c(a,"NintendoBrowser/"),H=!0;else if("Nintendo 3DS"===p){h="N3DS";g=c(a,"Version/");u=535;var rb=g;H=!0}else if("Nintendo Swicth"===p)h="Swicth",g=c(t,"NintendoBrowser/"),H=!0;else if("Nintendo WiiU"===p)h="WiiU",g=c(t,"NintendoBrowser/"),u=c(t,"AppleWebKit/"),H=!0;else if("Nintendo Wii"===p){h="Wii";g=c(a,"Wii; U; ; ");var d=h,e=g;H=!0}else if(b=
c(a,"PlayStation Vita "))h="PSVita",g=b,d=h,e=b,H=!0;else if(b=c(a,"(PlayStation Portable); ")){h="PSP";g=b;var eb=3.3;d=h;e=b;H=!0}else if(b=c(a,"PLAYSTATION 3; ")||c(a,"PLAYSTATION 3 ")){h="PS3";g=b;d=h;e=b;if(0>Ja("4.10",b))var m="Sony",n=b;H=!0}else if(f(a,"Xbox One"))h="XboxOne",g=1,H=!0;else if(f(a,"Xbox"))h="Xbox360",g=1,H=!0;else if(2===pa&&f(a,"Sony/COM2/")){h="Mylo";g=2;eb=3.4;d=h;e=2;var aa=!0}else if(0===p.indexOf("iP")||va||Y||xa){if(Y)switch(g=Y,ka.substr(0,4)){case "iPho":var w="iPhone",
O=c(ka,w),D=!0;break;case "iPad":w="iPad";O=c(ka,w);var x=!0;break;case "iPod":w="iPod";O=c(ka,w);var Da=!0}else{if(va)g=va;else{g=c(t.split("_").join("."),"OS ");var sb=!ba("isSecureContext",l),tb=ba("enableWebGL",l),ub=ba("sameOrigin",l)}g||(C=!0);if(!g||Ua)g=l.PointerEvent?13:l.HTMLDataListElement?12.2:Array.prototype.flat?12:I.sendBeacon?11.3:l.WebAssembly?11.2:l.HTMLMeterElement?10.3:l.Proxy?10.2:l.HTMLPictureElement?9.3:X.isNaN?9.2:l.SharedWorker?Ma&&Ma.now?8:8.4:ob?7.1:l.webkitURL?6.1:l.Worker?
5.1:Na?4.3:La?4.1:3.2;var Ea=1===l.devicePixelRatio,y=sa===1.5*ta||1.5*sa===ta;0===p.indexOf("iPhone")?(w="iPhone",O=y?Ea?{max:3}:{min:4,max:5}:{max:6},D=!0):0===p.indexOf("iPad")||xa?(w="iPad",O=Ea?{max:2}:{min:3},x=!0):0===p.indexOf("iPod")&&(w="iPod",O=y?Ea?{max:3}:4:{min:5},Da=!0)}if(!Y&&(I.standalone||(x||12>g)&&ba("webkitFullscreenEnabled",E)||11<=g&&13>g&&I.mediaDevices))m="SafariMobile",d="Safari",e=g;else{var Fa=!0;m="iOSWebView"}h="iOS";n=g}else if(f(a,"Kobo"))h="Kobo",m="AOSP",n=2.2,d=
m,e=n,G=la=!0;else if(f(a,"EBRD"))h="SonyReader",m="AOSP",n=2.2,d=m,e=n,la=!0;else if(b=c(a,"CrOS x86_64 ")||c(a,"CrOS aarch64 ")||c(a,"CrOS i686 ")||c(a,"CrOS armv7l ")){h="ChromeOS";g=b;var ma=!0}else if(void 0!==l.onmoztimechange)h="FirefoxOS",g=18.1>J?"1.0.1":19>J?1.1:27>J?1.2:29>J?1.3:31>J?1.4:33>J?2:35>J?2.1:38>J?2.2:45>J?2.5:2.6,f(a,"Mobile")?D=!0:f(a,"Tablet")?x=!0:f(a,"TV")&&(Z=!0);else if(l.palmGetResource)h="webOS",g=c(a,"webOS/")||c(a,"WEBOS")||c(a,"hpwOS/"),d=h,e=g,f(a,"webOS.TV")||f(a,
"/SmartTV")?Z=!0:D=!0;else if(b=c(a,"Tizen "))h="Tizen",g=b,d="Samsung",e=V,m=d,n=e,D=!0;else if(b=c(a,"Windows Phone ")||c(t,"Windows Phone OS ")||ib){var na=!0;g=b;D=!0}else if(fa&&"ARM"===p)na=!0,g=10,C=D=!0;else if(W&&f(t,"ZuneWP"))na=!0,g=11===F?8.1:10===F?8:9===F?7.5:7===F?7:"?",C=D=!0;else if(f(a,"FOMA;"))h="FeaturePhone",D=!0;else if(f(a,"SoftBank;"))h="FeaturePhone",D=!0;else if(f(a,"KFMUWI")){var K=!0;g=6.3;var A=x=!0}else if(f(a,"KFKAWI"))K=!0,g=6,A=x=!0;else if(f(a,"KFSUWI")||f(a,"KFAUWI")||
f(a,"KFDOWI"))K=!0,g=5,A=x=!0;else if(f(a,"KFGIWI"))K=!0,g=5,A=x=!0;else if(f(a,"KFARWI")||f(a,"KFSAWA")||f(a,"KFSAWI"))K=!0,g=5<=B(z)?5:4,A=x=!0;else if(f(a,"KFSOWI")||f(a,"KFTHWA")||f(a,"KFTHWI")||f(a,"KFAPWA")||f(a,"KFAPWI"))K=!0,g=3,A=x=!0;else if(f(a,"KFOT")||f(a,"KFTT")||f(a,"KFJWA")||f(a,"KFJWI"))K=!0,g=2,A=x=!0;else if(f(a,"Kindle Fire"))K=!0,g=1,A=x=!0;else if(b=c(a,"Kindle/"))h="Kindle",g=b,m="AOSP",n=2.2,d=m,e=n,la=!0;else if(pb)K=!0,g=z||db,A=Z=!0,C=db;else if(f(a,"AmazonWebAppPlatform")||
f(a,"; AFT"))K=!0,g=z,A=Z=!0;else if(f(a,"MeeGo"))h="MeeGo";else if(f(a,"Maemo"))h="Maemo";else if(0===a.indexOf("Windows Mobile;")||Va)h="WindowsMobile",aa=!0;else if("WinCE"===p)h=p,aa=!0;else if("Win16"===p||"Win32"===p||"Win64"===p)h=p,g=c(a,"Windows NT ")||c(a,"Windows "),ma=!0;else if(0===p.indexOf("Mac")){h="MacPowerPC"===p?"MacPPC":p;if(b=c(a.split("_").join("."),"Mac OS X "))g=b;var fb=ma=!0}else if(f(a,"BlackBerry")||f(a,"BB10"))h="BlackBerry",g=M,D=!0;else if(f(a,"SunOS")||f(a,"Sun Solaris"))h=
"SunOS",ma=!0;else if(f(a,"FreeBSD"))h="FreeBSD";else if(f(a,"OpenBSD"))h="OpenBSD";else if(f(a,"NetBSD"))h="NetBSD";else if(G&&U)f(a,"Android 4.4;")?y={min:2.3}:4<=B(z)?y=z:y={min:2.2},g=y,Za&&(C=!0);else if(G&&S)z?y=z:(y={min:1.6},C=!0),g=y,f(a,"Tablet")?x=!0:D=!0;else if(z)g=z,G=!0;else if(wa&&Za||$a||ab){var P=!0;V?y={min:4.4}:T&&!Xa||Qa||ia?y={min:4}:(y=z=void 0!==Ka.touchAction?{min:5}:Ba?4.4:Na?I.connection?l.searchBoxJavaBridge_||T?X.isNaN?4.1:4:4.2:4.4:534<=u?3:533<=u?La?2.3:2.2:530<=u?2:
1.5,Wa&&(m="Samsung",n=Wa));g=y;G=!0}else cb?(g={min:5},P=G=!0):wa&&(f(a,"Ubuntu")?h="Ubuntu":(b=c(a,"Mint/"))?(h="Mint",g=b):(b=c(a,"Fedora/"))?(h="Fedora",g=b):h=f(a,"Gentoo")?"Gentoo":"Linux");K||G&&P&&Aa?h="FireOS":G&&(h=h||"Android");na&&(h="WindowsPhone");if(!m)if(A=A||G,S)m=A||aa||D||x?"PrestoMobile":"Presto",n=Pa;else if(W)(y=R(t,"Trident/")+4)&&y!==F&&(d="IEHost",e=y),10<=F&&6.2<=g&&7>g&&0===screenY&&innerHeight+1!==outerHeight&&(d="ModernIE",e=F),aa||D||x||Da?m="TridentMobile":fb&&5<=F?
(m="Tasman",d="MacIE",e=F):(m="Trident",fb&&(d="MacIE",e=F)),n=F;else if(fa)m=na?"EdgeMobile":"EdgeHTML",n=c(t,"Edge/");else if(ya)m="Goanna",n=ya;else if(U)m=A?"Fennec":"Gecko",n=J||Sa;else if(V)m="Samsung",n=V,P&&(C=!0);else if(b=eb||c(a,"NetFront/"))m="NetFront",n=b;else if(b=c(a,"iCab"))m="iCab",n=b;else if(b=Ia(c(a,"Opera Mini/"),c(a,"Opera Mobi/"))||Oa&&M)m="OperaMini",n=b,h||(f(a,"iPhone")?w="iPhone":f(a,"iPad")?w="iPad":f(a,"iPod")&&(w="iPod"),w&&(h="iOS"));else if(ha)m="UCWEB",n=hb;else if(kb)m=
"KHTML",n=pa;else if(G&&Xa){m="AOSP";n=z;var oa=!0;P&&(C=!0)}else T||Qa||ia?(m=A?"ChromiumMobile":"Chromium",n=N,P&&(C=!0)):G&&Ba?(m="ChromeWebView",n=5>B(z)?z:N,oa=!0,l.requestFileSystem||l.webkitRequestFileSystem||(Ca=!0),P&&(C=!0)):G&&(M||P)?(m="AOSP",n=z,oa=!0,P&&(C=!0)):N?(m=A?"ChromiumMobile":"Chromium",n=N):u&&(m="WebKit",n=u);d||((b=fa&&c(a,"Edge/")||c(a,"EdgA/")||mb||c(a,"Edg/"))?(d="Edge",e=b):(b=c(t,"Coast/"))?(d="Coast",e=b):sb?d="OperaTurbo":(b=c(t,"OPT/"))?(d="OperaTouch",e=b,C=C||!f(t,
"Mobile/")):(b=c(a.toLowerCase(),"ybrowser/"))?(d="Yahoo",e=b):!ha&&(b=c(a,"UCBrowser/"))?(d="UC",e=b):Aa?(d="Silk",e=Aa):(b=c(a,"Vivaldi/"))?(d="Vivaldi",e=b):(b=c(a,"QQBrowser/"))?(d="QQ",e=b):(b=c(a,"YaBrowser/"))?(d="Yandex",e=b):(b=c(a,"coc_coc_browser/"))?(d="coccoc",e=b):(b=c(a,"Camino/"))?(d="Camino",e=b):f(a,"SE 2.X MetaSr 1.0")?d="Sogou":(b=c(a,"Focus/")||c(a,"Klar/")||9>B(za)&&Fa&&11<=B(g)&&za)?(d="Focus",e=b):(b=c(a,"AOLBUILD/")||c(a,"AOL/")||c(a,"AOL "))?(d="AOL",e=b):(b=c(a,"IceDragon/"))?
(d="IceDragon",e=b):(b=c(a,"Iceweasel/"))?(d="Iceweasel",e=b):(b=c(a,"TenFourFox/"))?(d="ITenFourFox",e=b):(b=c(a,"Waterfox/"))?(d="Waterfox",e=b):(b=c(a,"GNUzilla/"))?(d="GNUzilla",e=b):(b=c(a,"SeaMonkey/"))?(d="SeaMonkey",e=b):(b=c(a,"PaleMoon/"))?(d="PaleMoon",e=b):(b=c(a,"Basilisk/"))?(d="Basilisk",e=b):(b=c(a,"Maxthon/")||c(a,"Maxthon ")||c(a,"MXiOS/"))||f(a,"Maxthon")?(d="Maxthon",e=b||1):f(a,"Avant Browser;")?d="Avant":(b=c(a,"Konqueror/"))?(d="Konqueror",e=b):(b=c(a,"Midori/"))?(d="Midori",
e=b):(b=c(a,"OmniWeb/"))?(d="OmniWeb",e=b):(b=c(a,"Roccat/"))?(d="Roccat",e=b):(b=c(a,"Epiphany/"))?(d="Epiphany",e=b):(b=c(a,"WebPositive/"))?(d="WebPositive",e=b):(b=c(a,"Iron/"))||f(a," Iron ")?(d="Iron",e=b||T&&N):(b=c(a,"Comodo Dragon/"))?(d="ComodoDragon",e=b):(b=c(a,"Brave/"))||f(a," Brave ")||ub?(d="Brave",e=b||T&&N):(b=c(a,"Rockmelt/"))?(d="Rockmelt",e=b):(b=c(a,"Sleipnir/"))||Ua||ab?(d="Sleipnir",b&&(e=b)):tb?d="Dolphin":(b=c(a,"Puffin/"))?(d="Puffin",e=b):(b=c(a,"Dooble/"))?(d="Dooble",
e=b):(b=c(a,"Flock/"))?(d="Flock",e=b):(b=c(a,"Galeon/"))?(d="Galeon",e=b):(b=c(a,"Falkon/"))?(d="Falkon",e=b):(b=c(a,"Iceape/"))?(d="Iceape",e=b):(b=c(a,"K-Meleon/"))?(d="KMeleon",e=b):(b=rb||c(t,"NX/"))?(d="NetFrontNX",e=b):(b=c(a,"Netscape6/")||c(a,"Netscape/")||c(a,"Navigator/"))?(d="NN",e=b):Va?(d="Iris",e=b):(b=c(a,"FBAV/")||f(t,"FBAN/"))?(d="Facebook",e=b):(b=c(t,"Line/"))?(d="LINE",e=b):(b=c(a,"QtWebEngine/"))?(d="QtWebEngine",e=b):(b=c(a,"QtWebKit/"))?(d="QtWebKit",e=b):(b=c(a,"DuckDuckGo/"))?
(d="DuckDuckGo",e=b):(b=c(a,"Lunascape/")||$a)?(d="Lunascape",e=b):(b=za||U&&(Sa||n))?(d="Firefox",e=b):qb?(d="OperaGX",e=ia):(b=Pa||ia||Ta)?(d="Opera",e=b):W?(d="IE",e=n):V?(d=m,e=V):(b=lb||(T||cb&&oa)&&N)?(d="Chrome",e=b):oa&&!Ca?(d=m,e=n):Fa&&!x?(m="SafariMobile",d="Safari",e=g):Fa||Ca||!f(a,"Safari")&&!M||(d="Safari",e=M||(73>u?.8:85>u?.9:100>u?1:125>u?1.1:312>u?1.2:412>u?1.3:419.3>=u?2:525.13>=u?3:525.25>=u?3.1:3.2)),d=d||"unknown");h&&(q.PLATFORM=h,g?(q.PLATFORM_VERSION=da(g),q[h]=ea(g)):q[h]=
!0);m&&(q.ENGINE=m,n?(q.ENGINE_VERSION=da(n),q[m]=ea(n)):q[m]=!0,d||(d=m,e=n));d&&(q.BRAND=d,e?(q.BRAND_VERSION=da(e),q[d]=ea(e)):q[d]=!0);w&&(q.DEVICE=w,O?(q.DEVICE_VERSION=da(O),q[w]=ea(O)):q[w]=!0);if(C||xa)q.PCSITE_REQUESTED=!0;q.DEVICE_TYPE=aa?8:H?7:Z?6:Da?5:la?4:D?2:x?3:ma?1:0})(Ga,window,document,navigator,screen,parseFloat,Number)})(whatBrowserAmI);
