const pkg             = require('./package.json'),
      gulp            = require('gulp'),
      ClosureCompiler = require('google-closure-compiler').gulp(),
      postProcessor   = require( 'es2-postprocessor' ),
      es2ToES3        = require( 'es2-to-es3' ),
      fs              = require('fs'),
      JSDOM           = require('jsdom').JSDOM,
      moduleName      = pkg.name,
      tempJsName      = 'temp.js',
      tempDir         = require('os').tmpdir() + '/' + moduleName,
      globalVariables = 'document,navigator,screen,parseFloat,Number',
      copyright       = moduleName + '@' + pkg.version + '\n' +
                       '(c) 2021-' + (new Date).getFullYear() + ' ' + pkg.author + '(' + pkg.homepage + '), ' + pkg.license + '.';

let minify       = false;
let uaObjectName = 'whatBrowserAmI';
let fileName     = 'front.js';
let outputDir    = './test';
let formatting   = 'PRETTY_PRINT';
let target       = 'index';
let funcConpare;

function createListFile( category, cb ){
    fs.readFile(
        '../i-am/src/js/iAm/CONST/Enum' + category + '.js',
        function( error, buffer ){
            if( !error ){
                const obj = eval(
                        '(' +
                            buffer.toString()
                                .split( 'iAm.Enum' + category + ' =' )[ 1 ]
                                .split( 'iAm.DEFINE.MINIFY' ).join( '' + minify )
                                .split( 'iAm.UNKNOWN_VALUE' ).join( minify ? '0' : '""' )
                                .split( '};' ).join( '}' ) +
                        ')'
                    ), list = [], result = [];

                for( var name in obj ){
                    list.push(
                        {
                            displayName : name.split( '$R' ).join( '®' ).split( '$TM' ).join( '™' ).split( '$_' ).join( '-' )
                                              .split( '_' ).join( ' ' ).split( '$VL' ).join( '|' ),
                            value       : obj[ name ]
                        }
                    );
                };
                list.sort(
                    function( a, b ){
                        return a.displayName.toLowerCase() > b.displayName.toLowerCase() ? 1 : -1;
                    }
                );
                while( list.length ){
                    let item = list.shift();
                    result.push( item.value, item.displayName );
                };
                fs.writeFile(
                    './src/js/catalog/' + category + 'ValueToDisplayLabel.js',
                    '// THIS FILE GENERATED BY "gulp dist", DONT EDIT!\n\n' +
                    'goog.provice( "catalog.' + category + 'ValueToDisplayLabel" )' +
                    'var ' + category + 'ValueToDisplayLabel = ' + JSON.stringify( result, null, '    ' ),
                    cb
                );
            };
        }
    );
};

gulp.task( '__common', gulp.series(
    function( cb ){
        createListFile( 'Platform', cb );
    },
    function( cb ){
        createListFile( 'Device', cb );
    },
    function( cb ){
        createListFile( 'DeviceType', cb );
    },
    function( cb ){
        createListFile( 'Engine', cb );
    },
    function( cb ){
        createListFile( 'Brand', cb );
    },
    function( cb ){
        fs.readFile( '../i-am/src/js/iAm/conpare.js',
            function( err, buffer ){
                if( !err ){
                    funcConpare = 'var ' + uaObjectName + '=' + ( minify ? '[]' : '{}' ) + ';' +
                                  uaObjectName + '.conpare = ' +
                                  buffer.toString().split( 'iAm.conpare = ' )[ 1 ];
                    cb();
                };
            }
        )
    },
    function(){
        return gulp
            .src(
                [
                    '../i-am/src/closure-primitives/base.js',
                    '../i-am/.submodules/es2-core/src/js/**/*.js',
                    '../i-am/src/js/**/*.js',
                    '../who/src/js/**/*.js',
                     './.submodules/es2-json/src/js/**/*.js',
                     './src/js/**/*.js'
                ]
            ).pipe(
                ClosureCompiler(
                    {
                        dependency_mode   : 'PRUNE',
                        entry_point       : 'goog:who.all',
                        compilation_level : 'ADVANCED',
                        define            : [
                            'iAm.DEFINE.MINIFY=' + minify,
                            'JSON2.DEFINE.USE_REPLACER=false'
                        ],
                        warning_level     : 'VERBOSE',
                        language_in       : 'ECMASCRIPT3',
                        language_out      : 'ECMASCRIPT3',
                        js_output_file    : uaObjectName + '.js',
                        output_wrapper    :
                            'goog.provide(' + uaObjectName + ');\n' + 
                            funcConpare +
                            '(function(ua){\n' +
                                '%output%\n' +
                            '})(' + uaObjectName + ');'
                    }
                )
            ).pipe(
                gulp.dest( tempDir )
            );
    }
));

gulp.task( '__main', gulp.series(
    function(){
        return gulp
            .src(
                [
                    '../i-am/src/closure-primitives/base.js',
                    '../i-am/src/js/**/*.js',
                    '../who/src/js/**/*.js',
                    tempDir + '/' + uaObjectName + '.js',
                    './src/js/**/*.js'
                ]
            ).pipe(
                ClosureCompiler(
                    {
                        dependency_mode   : 'PRUNE',
                        entry_point       : 'goog:page.' + target,
                        compilation_level : 'ADVANCED',
                        define            : [
                            'iAm.DEFINE.MINIFY=' + minify
                        ],
                        warning_level     : 'VERBOSE',
                        language_in       : 'ECMASCRIPT3',
                        language_out      : 'ECMASCRIPT3',
                        output_wrapper    :
                            '(function(window, ' + globalVariables + '){\n' +
                                '%output%\n' +
                            '})(this, ' + globalVariables + ');'
                    }
                )
            ).pipe(
                postProcessor.gulp(
                    {
                        hoist : true
                    }
                )
            ).pipe(
                ClosureCompiler(
                    {
                        // compilation_level : minify ? 'DEFAULT' : 'WHITESPACE_ONLY',
                        warning_level     : 'QUIET',
                        language_in       : 'ECMASCRIPT3',
                        language_out      : 'ECMASCRIPT3'
                    }
                )
            ).pipe(
                postProcessor.gulp(
                    {
                        minIEVersion    : 5,
                        minOperaVersion : 7,
                        minGeckoVersion : 0.6
                    }
                )
            ).pipe(
                ClosureCompiler(
                    {
                        compilation_level : 'WHITESPACE_ONLY',
                        warning_level     : 'QUIET',
                        formatting        : formatting,
                        js_output_file    : fileName,
                        output_wrapper    : '\/* ' + copyright + ' *\/\n' + '%output%'
                    }
                )
            ).pipe(
                es2ToES3.gulp(
                    {
                        minIEVersion : 5
                    }
                )
            ).pipe(
                gulp.dest( tempDir )
            );
    },
    function( cb ){
        fs.readFile( tempDir + '/' + fileName,
            function( error, buffer ){
                if( error ){
                    throw error;
                };
                var js = buffer.toString();

                fs.readFile( './src/front/html/' + target + '.html',
                    function( error, buffer ){
                        if( error ){
                            throw error;
                        };
                        var htmlString = buffer.toString(),
                            jsdom      = new JSDOM( htmlString ),
                            document   = jsdom.window.document,
                            script     = document.getElementsByTagName( 'script' )[ 0 ];
                        
                        script.textContent = js;
                        fs.writeFile( './docs/' + target + '.html', jsdom.serialize(),
                            function( error ){
                                if( error ){
                                    throw error;
                                };
                                cb();
                            }
                        );
                    }
                );
            }
        );
    }
));

gulp.task( 'dist', gulp.series(
    '__common',
    '__main',
    function( cb ){
        target = 'who';
        cb();
    },
    '__main'
));
