// THIS FILE GENERATED BY "gulp dist", DONT EDIT!

var device_typeList = [
    "CAR",
    "CAR",
    "EINK_READER",
    "EINK READER",
    "GAME",
    "GAME",
    "MEDIA_PLAYER",
    "MEDIA PLAYER",
    "PC",
    "PC",
    "PDA",
    "PDA",
    "PHONE",
    "PHONE",
    "TABLET",
    "TABLET",
    "TV",
    "TV",
    "",
    "UNKNOWN"
]