goog.provide( 'whatBrowserAmI.BRAND' );

goog.require( 'whatBrowserAmI.DEFINE.MINIFY' );

/** @enum {string|number} */
whatBrowserAmI.BRAND = {
    Unknown           : whatBrowserAmI.DEFINE.MINIFY ?  0 : '',
    AndroidBrowser    : whatBrowserAmI.DEFINE.MINIFY ?  1 : 'AndroidBrowser',
    AOL               : whatBrowserAmI.DEFINE.MINIFY ?  2 : 'AOL',
    Avant             : whatBrowserAmI.DEFINE.MINIFY ?  3 : 'Avant',
    Basilisk          : whatBrowserAmI.DEFINE.MINIFY ?  4 : 'Basilisk',
    Brave             : whatBrowserAmI.DEFINE.MINIFY ?  5 : 'Brave',
    Camino            : whatBrowserAmI.DEFINE.MINIFY ?  6 : 'Camino',
    Chrome            : whatBrowserAmI.DEFINE.MINIFY ?  7 : 'Chrome',
    coccoc            : whatBrowserAmI.DEFINE.MINIFY ?  8 : 'coccoc',
    ComodoDragon      : whatBrowserAmI.DEFINE.MINIFY ?  9 : 'ComodoDragon',
    Dolphin           : whatBrowserAmI.DEFINE.MINIFY ? 10 : 'Dolphin',
    Dooble            : whatBrowserAmI.DEFINE.MINIFY ? 11 : 'Dooble',
    DuckDuckGo        : whatBrowserAmI.DEFINE.MINIFY ? 12 : 'DuckDuckGo',
    Edge              : whatBrowserAmI.DEFINE.MINIFY ? 13 : 'Edge',
    Epiphany          : whatBrowserAmI.DEFINE.MINIFY ? 14 : 'Epiphany',
    Facebook          : whatBrowserAmI.DEFINE.MINIFY ? 15 : 'Facebook',
    Falkon            : whatBrowserAmI.DEFINE.MINIFY ? 16 : 'Falkon',
    Firefox           : whatBrowserAmI.DEFINE.MINIFY ? 17 : 'Firefox',
    FirefoxFocus      : whatBrowserAmI.DEFINE.MINIFY ? 18 : 'FirefoxFocus',
    Flock             : whatBrowserAmI.DEFINE.MINIFY ? 19 : 'Flock',
    Galeon            : whatBrowserAmI.DEFINE.MINIFY ? 20 : 'Galeon',
    GNUzilla          : whatBrowserAmI.DEFINE.MINIFY ? 21 : 'GNUzilla',
    iCab              : whatBrowserAmI.DEFINE.MINIFY ? 22 : 'iCab',
    Iceape            : whatBrowserAmI.DEFINE.MINIFY ? 23 : 'Iceape',
    IceDragon         : whatBrowserAmI.DEFINE.MINIFY ? 24 : 'IceDragon',
    Iceweasel         : whatBrowserAmI.DEFINE.MINIFY ? 25 : 'Iceweasel',
    InternetExplorer  : whatBrowserAmI.DEFINE.MINIFY ? 26 : 'InternetExplorer',
    Iris              : whatBrowserAmI.DEFINE.MINIFY ? 27 : 'Iris',
    Iron              : whatBrowserAmI.DEFINE.MINIFY ? 28 : 'Iron',
    KMeleon           : whatBrowserAmI.DEFINE.MINIFY ? 29 : 'KMeleon',
    Konqueror         : whatBrowserAmI.DEFINE.MINIFY ? 30 : 'Konqueror',
    LINE              : whatBrowserAmI.DEFINE.MINIFY ? 31 : 'LINE',
    Lunascape         : whatBrowserAmI.DEFINE.MINIFY ? 32 : 'Lunascape',
    Maxthon           : whatBrowserAmI.DEFINE.MINIFY ? 33 : 'Maxthon',
    Midori            : whatBrowserAmI.DEFINE.MINIFY ? 34 : 'Midori',
    Mozilla           : whatBrowserAmI.DEFINE.MINIFY ? 35 : 'Mozilla',
    NetFront          : whatBrowserAmI.DEFINE.MINIFY ? 36 : 'NetFront',
    NetFrontNX        : whatBrowserAmI.DEFINE.MINIFY ? 37 : 'NetFrontNX',
    NetscapeNavigator : whatBrowserAmI.DEFINE.MINIFY ? 38 : 'NetscapeNavigator',
    OmniWeb           : whatBrowserAmI.DEFINE.MINIFY ? 39 : 'OmniWeb',
    Opera             : whatBrowserAmI.DEFINE.MINIFY ? 40 : 'Opera',
    OperaCoast        : whatBrowserAmI.DEFINE.MINIFY ? 41 : 'OperaCoast',
    OperaGX           : whatBrowserAmI.DEFINE.MINIFY ? 42 : 'OperaGX',
    OperaTouch        : whatBrowserAmI.DEFINE.MINIFY ? 43 : 'OperaTouch',
    OperaTurbo        : whatBrowserAmI.DEFINE.MINIFY ? 44 : 'OperaTurbo',
    PaleMoon          : whatBrowserAmI.DEFINE.MINIFY ? 45 : 'PaleMoon',
    Puffin            : whatBrowserAmI.DEFINE.MINIFY ? 46 : 'Puffin',
    QQ                : whatBrowserAmI.DEFINE.MINIFY ? 47 : 'QQ',
    QtWebEngine       : whatBrowserAmI.DEFINE.MINIFY ? 48 : 'QtWebEngine',
    QtWebKit          : whatBrowserAmI.DEFINE.MINIFY ? 49 : 'QtWebKit',
    Roccat            : whatBrowserAmI.DEFINE.MINIFY ? 50 : 'Roccat',
    Rockmelt          : whatBrowserAmI.DEFINE.MINIFY ? 51 : 'Rockmelt',
    Safari            : whatBrowserAmI.DEFINE.MINIFY ? 52 : 'Safari',
    SamsungInternet   : whatBrowserAmI.DEFINE.MINIFY ? 53 : 'SamsungInternet',
    SeaMonkey         : whatBrowserAmI.DEFINE.MINIFY ? 54 : 'SeaMonkey',
    Silk              : whatBrowserAmI.DEFINE.MINIFY ? 55 : 'SilK',
    Sleipnir          : whatBrowserAmI.DEFINE.MINIFY ? 56 : 'Sleipnir',
    Sogou             : whatBrowserAmI.DEFINE.MINIFY ? 57 : 'Sogou',
    TenFourFox        : whatBrowserAmI.DEFINE.MINIFY ? 58 : 'TenFourFox',
    UC                : whatBrowserAmI.DEFINE.MINIFY ? 59 : 'UC',
    Vivaldi           : whatBrowserAmI.DEFINE.MINIFY ? 60 : 'Vivaldi',
    Waterfox          : whatBrowserAmI.DEFINE.MINIFY ? 61 : 'Waterfox',
    WebPositive       : whatBrowserAmI.DEFINE.MINIFY ? 62 : 'WebPositive',
    Yahoo             : whatBrowserAmI.DEFINE.MINIFY ? 63 : 'Yahoo',
    Yandex            : whatBrowserAmI.DEFINE.MINIFY ? 64 : 'Yandex',

    IEForMac          : whatBrowserAmI.DEFINE.MINIFY ? 65 : 'IEForMac',
    ModernIE          : whatBrowserAmI.DEFINE.MINIFY ? 66 : 'ModernIE'
};
