goog.provide( 'whatBrowserAmI.PLATFORM' );

goog.require( 'whatBrowserAmI.DEFINE.MINIFY' );

/** @enum {string|number} */
whatBrowserAmI.PLATFORM = {
    Unknown               : whatBrowserAmI.DEFINE.MINIFY ?  0 : '',
    NINTENDO_DS$TM        : whatBrowserAmI.DEFINE.MINIFY ?  1 : 'NintendoDS',
    NINTENDO_DSi$TM       : whatBrowserAmI.DEFINE.MINIFY ?  2 : 'NintendoDSi',
    NINTENDO_3DS$TM       : whatBrowserAmI.DEFINE.MINIFY ?  3 : 'Nintendo3DS',
    New_NINTENDO_3DS$TM   : whatBrowserAmI.DEFINE.MINIFY ?  4 : 'NewNintendo3DS',
    Wii$TM                : whatBrowserAmI.DEFINE.MINIFY ?  5 : 'Wii',
    WiiU$TM               : whatBrowserAmI.DEFINE.MINIFY ?  6 : 'WiiU',
    NINTENDO_SWITCH$TM    : whatBrowserAmI.DEFINE.MINIFY ?  7 : 'NintendoSwitch',
    PlayStation$RPortable : whatBrowserAmI.DEFINE.MINIFY ?  8 : 'PlayStationPortable',
    PlayStation$RVita     : whatBrowserAmI.DEFINE.MINIFY ?  9 : 'PlayStationVita',
    PlayStation$R3        : whatBrowserAmI.DEFINE.MINIFY ? 10 : 'PlayStation3', // PlayStation2 ?
    PlayStation$R4        : whatBrowserAmI.DEFINE.MINIFY ? 11 : 'PlayStation4',
    PlayStation$R5        : whatBrowserAmI.DEFINE.MINIFY ? 12 : 'PlayStation5',
    Xbox_360$TM           : whatBrowserAmI.DEFINE.MINIFY ? 13 : 'Xbox360',
    Xbox_One$TM           : whatBrowserAmI.DEFINE.MINIFY ? 14 : 'XboxOne',
    Xbox_SeriesX$VLS      : whatBrowserAmI.DEFINE.MINIFY ? 15 : 'XboxSeries',
    Feature_Phone         : whatBrowserAmI.DEFINE.MINIFY ? 16 : 'FeaturePhone',
    SONY_mylo             : whatBrowserAmI.DEFINE.MINIFY ? 17 : 'mylo',
    Rakuten_Kobo          : whatBrowserAmI.DEFINE.MINIFY ? 18 : 'Kobo',
    SONY_Reader$R         : whatBrowserAmI.DEFINE.MINIFY ? 19 : 'SonyReader',
    Kindle                : whatBrowserAmI.DEFINE.MINIFY ? 20 : 'Kindle',
    Windows_CE            : whatBrowserAmI.DEFINE.MINIFY ? 21 : 'WindowsCE',
    Windows_Mobile        : whatBrowserAmI.DEFINE.MINIFY ? 22 : 'WindowsMobile',
    Windows_Phone         : whatBrowserAmI.DEFINE.MINIFY ? 23 : 'WindowsPhone',
    iOS                   : whatBrowserAmI.DEFINE.MINIFY ? 24 : 'iOS',
    iPadOS                : whatBrowserAmI.DEFINE.MINIFY ? 25 : 'iPadOS',
    WatchOS               : whatBrowserAmI.DEFINE.MINIFY ? 26 : 'WatchOS', 
    Android               : whatBrowserAmI.DEFINE.MINIFY ? 27 : 'Android',
    AndroidTV             : whatBrowserAmI.DEFINE.MINIFY ? 28 : 'AndroidTV',
    GoogleTV              : whatBrowserAmI.DEFINE.MINIFY ? 29 : 'GoogleTV',
    FireOS                : whatBrowserAmI.DEFINE.MINIFY ? 30 : 'FireOS',
    ChromeOS              : whatBrowserAmI.DEFINE.MINIFY ? 31 : 'ChromeOS',
    FirefoxOS             : whatBrowserAmI.DEFINE.MINIFY ? 32 : 'FirefoxOS',
    KaiOS                 : whatBrowserAmI.DEFINE.MINIFY ? 33 : 'KaiOS',
    Symbian_OS_S60        : whatBrowserAmI.DEFINE.MINIFY ? 34 : 'SymbianS60',
    MeeGo                 : whatBrowserAmI.DEFINE.MINIFY ? 35 : 'MeeGo',
    Maemo                 : whatBrowserAmI.DEFINE.MINIFY ? 36 : 'Maemo',
    WebOS                 : whatBrowserAmI.DEFINE.MINIFY ? 37 : 'WebOS',
    Tizen                 : whatBrowserAmI.DEFINE.MINIFY ? 38 : 'Tizen',
    BlackBerry            : whatBrowserAmI.DEFINE.MINIFY ? 39 : 'BlackBerry',
    Windows16             : whatBrowserAmI.DEFINE.MINIFY ? 40 : 'Windows16',
    Windows               : whatBrowserAmI.DEFINE.MINIFY ? 41 : 'Windows',
    Mac                   : whatBrowserAmI.DEFINE.MINIFY ? 42 : 'Mac',
    SunOS                 : whatBrowserAmI.DEFINE.MINIFY ? 43 : 'SunOS',
    FreeBSD               : whatBrowserAmI.DEFINE.MINIFY ? 44 : 'FreeBSD',
    OpenBSD               : whatBrowserAmI.DEFINE.MINIFY ? 45 : 'OpenBSD',
    NetBSD                : whatBrowserAmI.DEFINE.MINIFY ? 46 : 'NetBSD',
    Ubuntu                : whatBrowserAmI.DEFINE.MINIFY ? 47 : 'Ubuntu',
    Mint                  : whatBrowserAmI.DEFINE.MINIFY ? 48 : 'Mint',
    Fedora                : whatBrowserAmI.DEFINE.MINIFY ? 49 : 'Fedora',
    Gentoo                : whatBrowserAmI.DEFINE.MINIFY ? 50 : 'Gento',
    Linux                 : whatBrowserAmI.DEFINE.MINIFY ? 51 : 'Linux'
};