var
    /** @define {boolean} */
    DEFINE_WHAT_BROWSER_AM_I__MINIFY                   = false,
    /** @define {boolean} */
    DEFINE_WHAT_BROWSER_AM_I__BRAND_ENABLED            = true,
    /** @define {boolean} */
    DEFINE_WHAT_BROWSER_AM_I__PCSITE_REQUESTED_ENABLED = true,
    /** @define {boolean} */
    DEFINE_WHAT_BROWSER_AM_I__IOS_DEVICE_ENABLED       = true,
    /** @define {boolean} */
    DEFINE_WHAT_BROWSER_AM_I__DEVICE_TYPE_ENABLED      = true;

var WHAT_BROWSER_AM_I__INDEX_ENGINE           = DEFINE_WHAT_BROWSER_AM_I__MINIFY ? 0 : 'ENGINE',
    WHAT_BROWSER_AM_I__INDEX_ENGINE_VERSION   = DEFINE_WHAT_BROWSER_AM_I__MINIFY ? 1 : 'ENGINE_VERSION',
    WHAT_BROWSER_AM_I__INDEX_PLATFORM         = DEFINE_WHAT_BROWSER_AM_I__MINIFY ? 2 : 'PLATFORM',
    WHAT_BROWSER_AM_I__INDEX_PLATFORM_VERSION = DEFINE_WHAT_BROWSER_AM_I__MINIFY ? 3 : 'PLATFORM_VERSION',
    WHAT_BROWSER_AM_I__INDEX_BRAND            = DEFINE_WHAT_BROWSER_AM_I__MINIFY ? 4 : 'BRAND',
    WHAT_BROWSER_AM_I__INDEX_BRAND_VERSION    = DEFINE_WHAT_BROWSER_AM_I__MINIFY ? 5 : 'BRAND_VERSION',
    WHAT_BROWSER_AM_I__INDEX_DEVICE           = DEFINE_WHAT_BROWSER_AM_I__MINIFY ? 6 : 'DEVICE',
    WHAT_BROWSER_AM_I__INDEX_DEVICE_VERSION   = DEFINE_WHAT_BROWSER_AM_I__MINIFY ? 7 : 'DEVICE_VERSION',
    WHAT_BROWSER_AM_I__INDEX_DEVICE_TYPE      = DEFINE_WHAT_BROWSER_AM_I__MINIFY ? 8 : 'DEVICE_TYPE',
    WHAT_BROWSER_AM_I__INDEX_PCSITE_REQUESTED = DEFINE_WHAT_BROWSER_AM_I__MINIFY ? 9 : 'PCSITE_REQUESTED';