var WHAT_BROWSER_AM_I__DEVICE_iPhone = DEFINE_WHAT_BROWSER_AM_I__MINIFY ? 0 : 'iPhone',
    WHAT_BROWSER_AM_I__DEVICE_iPad   = DEFINE_WHAT_BROWSER_AM_I__MINIFY ? 1 : 'iPad',
    WHAT_BROWSER_AM_I__DEVICE_iPod   = DEFINE_WHAT_BROWSER_AM_I__MINIFY ? 2 : 'iPod';