var IZ_UA_DETECTOR_DEFINE_BRAND_ENABLED       = true,
    IZ_UA_DETECTOR_DEFINE_PC_MODE_ENABLED     = true,
    IZ_UA_DETECTOR_DEFINE_IOS_DEVICE_ENABLED  = true,
    IZ_UA_DETECTOR_DEFINE_DEVICE_TYPE_ENABLED = true;